spring.application.name=Mavli
spring.datasource.url=jdbc:postgresql://localhost:5432/sms_db
spring.datasource.username=postgres
spring.datasource.password=bantya bhi
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true